---
title: "REFMAP Listening test 1 Parts A & B analysis: Bayesian mixed models for inferential explanation"
output: html_document
date: "2026-05-07"
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
library(conflicted)
library(brms)
library(bayestestR)
library(tidybayes)
library(bayesplot)
library(easystats)
library(tidyverse)
library(DHARMa)
library(tictoc)
library(future)
library(mice)
library(marginaleffects)
library(priorsense)
library(posterior)
library(loo)
library(shinystan)
library(shinybrms)

# set package parameters
theme_set(theme_bw())

n_cores <- max(1, parallel::detectCores() - 4)
future::plan(future::multisession, workers = n_cores)

options(marginaleffects_parallel_inferences = TRUE)
options(marginaleffects_parallel_packages = c("marginaleffects", "brms"))

set.seed(808)

```

# Import data and wrangle

## Parts A & B combined

```{r}

subjDataPath <- utils::choose.files(caption=r"(Select refmap_listest1_testdata_BySubj.csv from 03 Experiment\Experiment 1\Analysis\PostProcess)",
                                     filters=matrix(data=c("refmap_listest1_testdata_BySubj.csv", "refmap_listest1_testdata_BySubj.csv"), ncol=2))

subjData <- read.csv(subjDataPath, header=TRUE)

stimDataPath <- utils::choose.files(caption=r"(Select refmap_listest1_testdata_ByStim.csv from 03 Experiment\Experiment 1\Analysis\PostProcess)",
                                     filters=matrix(data=c("refmap_listest1_testdata_ByStim.csv", "refmap_listest1_testdata_ByStim.csv"), ncol=2))

stimData <- read.csv(stimDataPath, header=TRUE, row.names=1)

```

```{r}
# definition of ordinal variable levels
UASLAeqCatsA <- c("Baseline", "42", "48", "54", "60")
SNRCatsA <- c("Baseline", "-16", "-10", "-4", "2", "8")
UASOpCatsA <- c("Baseline", "Overflight", "Landing", "Takeoff")
UASTypeCatsA <- c("Baseline", "H520", "M300", "T150")

# encode factors
subjData$ID <- factor(subjData$ID)
subjData$UASLAeq <- factor(subjData$UASLAeq, levels=UASLAeqCatsA, order=TRUE)
subjData$SNRlevel <- factor(subjData$SNRlevel, levels=SNRCatsA, order=TRUE)
subjData$UASOperation <- factor(subjData$UASOperation, levels=UASOpCatsA)
subjData$UASType <- factor(subjData$UASType, levels=UASTypeCatsA)
subjData$AmbientEnv <- factor(subjData$AmbientEnv, levels=c("Park", "Street"))
subjData$AAM_attitude <- factor(subjData$AAM_attitude)
subjData$Home_Area <- factor(subjData$Home_Area)
subjData$Area_soundscape <- factor(subjData$Area_soundscape)
subjData$NationGeo <- factor(subjData$NationGeo)

# recode AAM_attitude to 3 groups
subjData <- subjData |> dplyr::mutate(AAM_attitude3 = case_match(AAM_attitude,
                                                                    "Supportive" ~ "Supportive",
                                                                    c("Ambivalent",
                                                                      "Concerned") ~ "Ambiv_Concern",
                                                                      "Neutral" ~ "Neutral"))
subjData$AAM_attitude3 <- factor(subjData$AAM_attitude3)

# recode AAM_attitude to 2 groups
subjData <- subjData |> dplyr::mutate(AAM_attitude2 = case_match(AAM_attitude,
                                                                    "Supportive" ~ "Supportive",
                                                                    c("Ambivalent",
                                                                      "Concerned",
                                                                      "Neutral") ~ "Ambiv_Concern_Neutral"))
subjData$AAM_attitude2 <- factor(subjData$AAM_attitude2)

# recode AAM_attitude to 2 other groups
subjData <- subjData |> dplyr::mutate(AAM_attitude2_2 = case_match(AAM_attitude,
                                                                    c("Supportive",
                                                                      "Ambivalent") ~ "Support_Ambiv",
                                                                    c("Concerned",
                                                                      "Neutral") ~ "Concern_Neutral"))

subjData$AAM_attitude2_2 <- factor(subjData$AAM_attitude2_2)

# recode NationGeo to 4 groups
subjData <- subjData |> dplyr::mutate(NationGeo4 = case_match(NationGeo,
                                                               "UK" ~ "UK",
                                                               c("Africa",
                                                                 "SouthAsia") ~ "Africa_SAsia",
                                                               c("Australasia",
                                                                 "EastAsia",
                                                                 "Europe",
                                                                 "MidEast",
                                                                 "SouthAmerica") ~ "Other",
                                                               "" ~ "Unspecified"))
subjData$NationGeo4 <- factor(subjData$NationGeo4)

# recode NationGeo to 3 groups
subjData <- subjData |> dplyr::mutate(NationGeo3 = case_match(NationGeo,
                                                                 "UK" ~ "UK",
                                                                 c("Africa",
                                                                   "SouthAsia") ~ "Africa_SAsia",
                                                                 c("Australasia",
                                                                   "EastAsia",
                                                                   "Europe",
                                                                   "MidEast",
                                                                   "SouthAmerica",
                                                                   "") ~ "Other"))
subjData$NationGeo3 <- factor(subjData$NationGeo3)

# recode NationGeo to 2 groups
subjData <- subjData |> dplyr::mutate(NationGeo2 = case_match(NationGeo,
                                                                 "UK" ~ "UK",
                                                                 c("Africa",
                                                                   "SouthAsia",
                                                                   "Australasia",
                                                                   "EastAsia",
                                                                   "Europe",
                                                                   "MidEast",
                                                                   "SouthAmerica",
                                                                   "") ~ "Other"))
subjData$NationGeo2 <- factor(subjData$NationGeo2)


subjData$NationGeo3 <- factor(subjData$NationGeo3)

# recode Area of residence to 2 groups
subjData <- subjData |> dplyr::mutate(Home_Area2 = case_match(Home_Area,
                                                         "Urban" ~ "Urban",
                                                         c("Suburban",
                                                           "Rural") ~ "Suburban_Rural"))
subjData$Home_Area2 <- factor(subjData$Home_Area2)


# recode Area soundscape to 2 groups
subjData <- subjData |> dplyr::mutate(Area_soundscape2 = case_match(Area_soundscape,
                                                                       c("Calm",
                                                                         "Monotonous") ~ "Uneventful",
                                                                       c("Chaotic",
                                                                         "Vibrant") ~ "Eventful"))

subjData$Area_soundscape2 <- factor(subjData$Area_soundscape2)

# rescale trial number variables separately for each session part
subjData <- rbind(subjData[subjData$SessionPart == "A", ] |> dplyr::mutate(PartTrialNumberScl = datawizard::standardise(PartTrialNumber, scale=TRUE)),
                    subjData[subjData$SessionPart == "B", ] |> dplyr::mutate(PartTrialNumberScl = datawizard::standardise(PartTrialNumber, scale=TRUE)))
subjData <- subjData |> dplyr::mutate(TrialNumberScl = datawizard::standardise(TrialNumber, scale=TRUE))

# relocate new columns
subjData <- subjData |> dplyr::relocate(TrialNumberScl, PartTrialNumberScl, .after=PartTrialNumber)

# rescale variables
subjData <- subjData |> dplyr::mutate(UASLAeqMaxLRScl = datawizard::standardise(UASLAeqMaxLR, scale=FALSE))
subjData <- subjData |> dplyr::mutate(UASLAEMaxLRScl = datawizard::standardise(UASLAEMaxLR, scale=FALSE))
subjData <- subjData |> dplyr::mutate(UASEPNLMaxLRScl = datawizard::standardise(UASEPNLMaxLR, scale=FALSE))
subjData <- subjData |> dplyr::mutate(LAELAF50diffScl = datawizard::standardise(LAELAF50diff, scale=FALSE))
subjData <- subjData |> dplyr::mutate(LAELAeqdiffScl = datawizard::standardise(LAELAeqdiff, scale=FALSE))
subjData <- subjData |> dplyr::mutate(EPNLLAeqdiffScl = datawizard::standardise(EPNLLAeqdiff, scale=FALSE))
subjData <- subjData |> dplyr::mutate(UASDisc0p5LAEMaxLRScl = datawizard::standardise(UASDisc0p5LAEMaxLR, scale=FALSE))
subjData <- subjData |> dplyr::mutate(UASDisc0p5PAEMaxLR = 2e-5*10^(UASDisc0p5LAEMaxLR/20))
subjData <- subjData |> dplyr::mutate(UASLoudECMAPowAvgBinScl = datawizard::standardise(UASLoudECMAPowAvgBin, scale=FALSE))
subjData <- subjData |> dplyr::mutate(IntermitRatioC2MaxLRScl = IntermitRatioC2MaxLR/100)
subjData <- subjData |> dplyr::mutate(IntermitRatioC3MaxLRScl = IntermitRatioC3MaxLR/100)
subjData <- subjData |> dplyr::mutate(IntermitRatioC5MaxLRScl = IntermitRatioC5MaxLR/100)
subjData <- subjData |> dplyr::mutate(AmbLAeqMaxLRScl = datawizard::standardise(AmbLAeqMaxLR, scale=FALSE))
subjData <- subjData |> dplyr::mutate(AmbLAF50ExMaxLRScl = datawizard::standardise(AmbLAF50ExMaxLR, scale=FALSE))


stimData <- stimData |> dplyr::mutate(UASLAeqMaxLRScl = datawizard::standardise(UASLAeqMaxLR, scale=FALSE))
stimData <- stimData |> dplyr::mutate(UASLAEMaxLRScl = datawizard::standardise(UASLAEMaxLR, scale=FALSE))
stimData <- stimData |> dplyr::mutate(UASEPNLMaxLRScl = datawizard::standardise(UASEPNLMaxLR, scale=FALSE))
stimData <- stimData |> dplyr::mutate(LAELAF50diffScl = datawizard::standardise(LAELAF50diff, scale=FALSE))
stimData <- stimData |> dplyr::mutate(LAELAeqdiffScl = datawizard::standardise(LAELAeqdiff, scale=FALSE))
stimData <- stimData |> dplyr::mutate(EPNLLAeqdiffScl = datawizard::standardise(EPNLLAeqdiff, scale=FALSE))
stimData <- stimData |> dplyr::mutate(UASDisc0p5LAEMaxLRScl = datawizard::standardise(UASDisc0p5LAEMaxLR, scale=FALSE))
stimData <- stimData |> dplyr::mutate(UASDisc0p5PAEMaxLR = 2e-5*10^(UASDisc0p5LAEMaxLR/20))
stimData <- stimData |> dplyr::mutate(UASLoudECMAPowAvgBinScl = datawizard::standardise(UASLoudECMAPowAvgBin, scale=FALSE))
stimData <- stimData |> dplyr::mutate(IntermitRatioC2MaxLRScl = IntermitRatioC2MaxLR/100)
stimData <- stimData |> dplyr::mutate(IntermitRatioC3MaxLRScl = IntermitRatioC3MaxLR/100)
stimData <- stimData |> dplyr::mutate(IntermitRatioC5MaxLRScl = IntermitRatioC5MaxLR/100)
stimData <- stimData |> dplyr::mutate(AmbLAeqMaxLRScl = datawizard::standardise(AmbLAeqMaxLR, scale=FALSE))
stimData <- stimData |> dplyr::mutate(AmbLAF50ExMaxLRScl = datawizard::standardise(AmbLAF50ExMaxLR, scale=FALSE))


# convert detectability dB to log variables
subjData <- subjData |> dplyr::mutate(Detect0p1IntMaxLRLog = Detect0p1dBIntMaxLR/10)
subjData <- subjData |> dplyr::mutate(Detect0p5IntMaxLRLog = Detect0p5dBIntMaxLR/10)
subjData <- subjData |> dplyr::mutate(Detect0p1MaxMaxLRLog = Detect0p1dBMaxMaxLR/10)
subjData <- subjData |> dplyr::mutate(Detect0p5MaxMaxLRLog = Detect0p5dBMaxMaxLR/10)
subjData <- subjData |> dplyr::mutate(Detect0p1IntMaxLRLogScl = datawizard::standardise(Detect0p1IntMaxLRLog, scale=FALSE))
subjData <- subjData |> dplyr::mutate(Detect0p5IntMaxLRLogScl = datawizard::standardise(Detect0p5IntMaxLRLog, scale=FALSE))
subjData <- subjData |> dplyr::mutate(Detect0p1MaxMaxLRLogScl = datawizard::standardise(Detect0p1MaxMaxLRLog, scale=FALSE))
subjData <- subjData |> dplyr::mutate(Detect0p5MaxMaxLRLogScl = datawizard::standardise(Detect0p5MaxMaxLRLog, scale=FALSE))

stimData <- stimData |> dplyr::mutate(Detect0p1IntMaxLRLog = Detect0p1dBIntMaxLR/10)
stimData <- stimData |> dplyr::mutate(Detect0p5IntMaxLRLog = Detect0p5dBIntMaxLR/10)
stimData <- stimData |> dplyr::mutate(Detect0p1MaxMaxLRLog = Detect0p1dBMaxMaxLR/10)
stimData <- stimData |> dplyr::mutate(Detect0p5MaxMaxLRLog = Detect0p5dBMaxMaxLR/10)
stimData <- stimData |> dplyr::mutate(Detect0p1IntMaxLRLogScl = datawizard::standardise(Detect0p1IntMaxLRLog, scale=FALSE))
stimData <- stimData |> dplyr::mutate(Detect0p5IntMaxLRLogScl = datawizard::standardise(Detect0p5IntMaxLRLog, scale=FALSE))
stimData <- stimData |> dplyr::mutate(Detect0p1MaxMaxLRLogScl = datawizard::standardise(Detect0p1MaxMaxLRLog, scale=FALSE))
stimData <- stimData |> dplyr::mutate(Detect0p5MaxMaxLRLogScl = datawizard::standardise(Detect0p5MaxMaxLRLog, scale=FALSE))

# Log other variables
subjData$PartLoudMGLT05ExLog <- log(subjData$PartLoudMGLT05Ex)
subjData$PartLoudMGST05ExLog <- log(subjData$PartLoudMGST05Ex)
subjData$PartLoudMGLTPowAvgLog <- log(subjData$PartLoudMGLTPowAvg)
subjData$PartLoudMGSTPowAvgLog <- log(subjData$PartLoudMGSTPowAvg)

stimData$PartLoudMGLT05ExLog <- log(stimData$PartLoudMGLT05Ex)
stimData$PartLoudMGST05ExLog <- log(stimData$PartLoudMGST05Ex)
stimData$PartLoudMGLTPowAvgLog <- log(stimData$PartLoudMGLTPowAvg)
stimData$PartLoudMGSTPowAvgLog <- log(stimData$PartLoudMGSTPowAvg)

# reorder by participant ID and trial number
subjData <- subjData[with(subjData, order(ID, TrialNumber)), ]

# omit ambient-only stimuli
subjDataNoAmb <- subjData |> dplyr::filter(UASLAeq != "Baseline")
stimDataNoAmb <- stimData |> dplyr::filter(UASLAeq != "Baseline")

# re-encode factors omitting ambient-only stimuli
subjDataNoAmb$SNRlevel <- factor(subjDataNoAmb$SNRlevel, levels=SNRCatsA[2:length(SNRCatsA)], order=TRUE)
subjDataNoAmb$UASOperation <- factor(subjDataNoAmb$UASOperation, levels=UASOpCatsA[2: length(UASOpCatsA)])
subjDataNoAmb$UASType <- factor(subjDataNoAmb$UASType, levels=UASTypeCatsA[2:length(UASTypeCatsA)])
stimDataNoAmb$SNRlevel <- factor(stimDataNoAmb$SNRlevel, levels=SNRCatsA[2:length(SNRCatsA)], order=TRUE)
stimDataNoAmb$UASOperation <- factor(stimDataNoAmb$UASOperation, levels=UASOpCatsA[2: length(UASOpCatsA)])
stimDataNoAmb$UASType <- factor(stimDataNoAmb$UASType, levels=UASTypeCatsA[2:length(UASTypeCatsA)])

# Convert Age variable to numeric
subjDataNoAmb <- subjDataNoAmb |> dplyr::mutate(Age=as.numeric(Age))

# re-encode dAnnoyance variable as ordinal
subjDataNoAmb <- subjDataNoAmb |> dplyr::mutate(dAnnoyanceOrd=factor(dAnnoyance, levels=seq(-10, 10, by=1), ordered=TRUE))


```

# dAnnoyance

## Priors

```{r}

priors1 <- c(
  brms::prior(normal(0.2, 0.5), class='b', coef='UASLAEMaxLRScl'),
  brms::prior(normal(-1.5, 0.75), class='b', coef='IUASEventsEM1'),
  brms::prior(normal(0, 0.5), class='b', coef='UASLAEMaxLRScl:IUASEventsEM1'),
  brms::prior(normal(0.1, 0.25), class='b', coef='TrialNumberScl'),
  brms::prior(normal(0, 0.5), class='b', coef='SessionPartB'),
  set_prior("normal(0, 1)", class = 'Intercept'),
  set_prior("normal(0, 0.5)", class='b')
)

```

## Model 1a: maximal model

```{r}

model1aformula <- dAnnoyanceOrd ~ 1 + TrialNumberScl +
                      SessionPart +
                   UASLAEMaxLRScl*AmbientEnv +
                   UASLAEMaxLRScl*I(UASEvents^-1) +
                   UASLAEMaxLRScl*UASOperation +
                   UASLAEMaxLRScl*UASType +
                   NationGeo2 + AAM_attitude + Home_Area2 +
                   Age + Sex + NSSTotal + NativeLang +
                   Area_soundscape + PANAS_positive +
                   PANAS_negative +
                   (1 + UASLAEMaxLRScl + AmbientEnv + I(UASEvents^-1) +
                      UASOperation + UASType | ID) +
                     (1 | StimID)

tic()
model1aPriors <- brms::brm(model1aformula,
                 data=subjDataNoAmb,
                 family=cumulative(link='logit'),
                 future=TRUE, backend='cmdstanr', prior = priors1,
                 sample_prior='only', seed=808,
                 chains=4, iter=2000, warmup=1000)
toc()

model1aPriorCheck <- brms::pp_check(model1aPriors, type='bars', ndraws = 100) +
  theme(panel.grid=element_blank(), text=element_text(family='serif')) +
  labs(x="Mean change in annoyance")
model1aPriorCheck

tic()
model1a <- brms::brm(model1aformula,
                 data=subjDataNoAmb,
                 family=cumulative(link='logit'),
                 future=TRUE, backend='cmdstanr', prior = priors1,
                 threads=threading(threads=3, static=TRUE),  # check threads*chains = n_cores
                 seed=808, chains=4, iter=2000, warmup=1000)
toc()

model1aPostCheck <- brms::pp_check(model1a, type='bars', ndraw=100) +
  theme(panel.grid=element_blank(), text=element_text(family='serif')) +
  labs(x="Ordinal category index")
model1aPostCheck

```

## Model 1b: omit stimID random effect

```{r}

model1bformula <- dAnnoyanceOrd ~ 1 + TrialNumberScl +
                      SessionPart +
                   UASLAEMaxLRScl*AmbientEnv +
                   UASLAEMaxLRScl*I(UASEvents^-1) +
                   UASLAEMaxLRScl*UASOperation +
                   UASLAEMaxLRScl*UASType +
                   NationGeo2 + AAM_attitude + Home_Area2 +
                   Age + Sex + NSSTotal + NativeLang +
                   Area_soundscape + PANAS_positive +
                   PANAS_negative +
                   (1 + UASLAEMaxLRScl + AmbientEnv + I(UASEvents^-1) +
                      UASOperation + UASType | ID)

tic()
model1b <- brms::brm(model1bformula,
                 data=insight::get_data(model1a),
                 family=cumulative(link='logit'),
                 future=TRUE, backend='cmdstanr', prior = priors1,
                 threads=threading(threads=3, static=TRUE), # check threads*chains = n_cores,
                 seed=303, chains=4, iter=2000, warmup=1000)
toc()

model1bPostCheck <- brms::pp_check(model1b, type='bars', ndraw=100) +
  theme(panel.grid=element_blank(), text=element_text(family='serif')) +
  labs(x="Ordinal category index")
model1bPostCheck

```

## Model 1a and 1b comparison

```{r}
model1a <- brms::add_criterion(model1a, criterion=c('loo', 'loo_R2'), cores=n_cores)
model1b <- brms::add_criterion(model1b, criterion=c('loo', 'loo_R2'), cores=n_cores)
```

```{r}

loo::loo(model1a)
loo::loo(model1b)

model1aVs1b_loo <- loo::loo_compare(model1a, model1b, criterion='loo')
model1aVs1b_loo

# elpd_diff se_diff
# model1a  0.0       0.0   
# model1b -3.5       1.6

```

```{r}

# #diagnostics
# posterior_m1b <- as.array(model1b)
# lp_m1b <- brms::log_posterior(model1b)
# np_m1b <- brms::nuts_params(model1b)
# 
# p_mcmc <- bayesplot::mcmc_parcoord(posterior_m1b, np=np_m1b)
# p_mcmc + ylim(-50, 50)
# 
# brms::mcmc_plot(model1b, type='rhat')
# brms::mcmc_plot(model1b, type='nuts_acceptance')
# brms::mcmc_plot(model1b, type='nuts_divergence')
# brms::mcmc_plot(model1b, type='trace_highlight', variable=c('b_UASLAEMaxLRScl', 'b_IUASEventsEM1', 'b_UASLAEMaxLRScl:IUASEventsEM1', 'b_NationGeo2UK'))

```

## Model 2: omit group slopes for UASOperation and UASType

```{r}
model2formula <- dAnnoyanceOrd ~ 1 + TrialNumberScl +
                      SessionPart +
                   UASLAEMaxLRScl*AmbientEnv +
                   UASLAEMaxLRScl*I(UASEvents^-1) +
                   UASLAEMaxLRScl*UASOperation +
                   UASLAEMaxLRScl*UASType +
                   NationGeo2 + AAM_attitude + Home_Area2 +
                   Age + Sex + NSSTotal + NativeLang +
                   Area_soundscape + PANAS_positive +
                   PANAS_negative +
                   (1 + UASLAEMaxLRScl + AmbientEnv + I(UASEvents^-1) | ID)

# update model1 with a reduced random effects structure
tic()
model2 <- brms::brm(model2formula,
                   data=insight::get_data(model1a),
                   family=cumulative(link='logit'),
                   future=TRUE, backend='cmdstanr', prior = priors1,,
                   threads=threading(threads=3, static=TRUE), # check threads*chains = n_cores
                   seed=707, chains=4, iter=2000, warmup=1000)
toc()

model2 <- brms::add_criterion(model2, criterion=c('loo', 'loo_R2'), cores=n_cores)

model2PostCheck <- brms::pp_check(model2, type='bars', ndraw=100) +
  theme(panel.grid=element_blank(), text=element_text(family='serif')) +
  labs(x="Ordinal category index")
model2PostCheck

```

## Model 1a and Model 2 comparison

```{r}

loo::loo(model1a)
loo::loo(model2)

model1aVs2_loo <- loo::loo_compare(model1a, model2, criterion='loo')
model1aVs2_loo

#         elpd_diff se_diff
# model1a   0.0       0.0  
# model2  -13.8       7.9 

```

## Model 3: omit group slope for 1/UASEvents

```{r}

model3formula <- dAnnoyanceOrd ~ 1 + TrialNumberScl +
                      SessionPart +
                   UASLAEMaxLRScl*AmbientEnv +
                   UASLAEMaxLRScl*I(UASEvents^-1) +
                   UASLAEMaxLRScl*UASOperation +
                   UASLAEMaxLRScl*UASType +
                   NationGeo2 + AAM_attitude + Home_Area2 +
                   Age + Sex + NSSTotal + NativeLang +
                   Area_soundscape + PANAS_positive +
                   PANAS_negative +
                   (1 + UASLAEMaxLRScl + AmbientEnv | ID)

# update model1 with a reduced random effects structure
tic()
model3 <- brms::brm(model3formula,
                   data=insight::get_data(model1a),
                   family=cumulative(link='logit'),
                   future=TRUE, backend='cmdstanr', prior = priors1,,
                   threads=threading(threads=3, static=TRUE), # check threads*chains = n_cores
                   seed=999, chains=4, iter=2000, warmup=1000)
toc()

model3 <- brms::add_criterion(model3, criterion=c('loo', 'loo_R2'), cores=n_cores)

model3PostCheck <- brms::pp_check(model3, type='bars', ndraw=100) +
  theme(panel.grid=element_blank(), text=element_text(family='serif')) +
  labs(x="Ordinal category index")
model3PostCheck

```

## Model 1a and Model 2 comparison

```{r}

loo::loo(model1a)
loo::loo(model2)
loo::loo(model3)

model1aVs2Vs3_loo <- loo::loo_compare(model1a, model1b, model2, model3, criterion='loo')
model1aVs2Vs3_loo

#         elpd_diff se_diff
# model1a    0.0       0.0 
# model1b   -3.5       1.6 
# model2   -13.8       7.9 
# model3  -187.7      18.6 

```


